### ISSUE TITLE
Run the code

### ISSUE THREAD

**Issue by sushree41** [zillow/zind#5]
Can you please provide the steps to run this code to get the test outputs

**Comment by zhiqiangw** [comment]
You can run the visualization script with `python code/visualize_zind_cli.py -i sample_tour -o <output_folder> --visualize-layout --visualize-floor-plan --raw --complete --visible --primary --secondary`
More examples about how to run the visualization script can be found [here](https://github.com/zillow/zind/blob/main/code/visualize_zind_cli.py#L14)
